---
  - name: Configure PostgreSQL host-based authentication
    template: src=pg_hba.conf.j2 dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    notify: restart postgresql
    become: yes

  - name: Configure PostgreSQL
    template: src=postgresql.conf.j2 dest=/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    notify: restart postgresql
    become: yes

  - name: Postgresql | Ensure postgres will trust local unix connections
    lineinfile: dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
      regexp='local\s+all\s+all'
      line='local all all trust'
      insertafter=EOF
      backrefs=yes
    notify: restart postgresql
    become: yes

  - name: Postgresql | Ensure postgres will trust local TCP/IP connections
    lineinfile: dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
      regexp='host\s+all\s+all\s+127.0.0.1/32'
      line='host all all 127.0.0.1/32 trust'
      insertafter=EOF
      backrefs=yes
    notify: restart postgresql
    become: yes

  - name: Postgresql | Ensure postgres allows all connections (DEV hosts)
    lineinfile: dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
      regexp='host\s+all\s+all\s+0.0.0.0/0\s+md5'
      line='host all all 0.0.0.0/0 md5'
      insertafter=EOF
    notify: restart postgresql
    become: yes
